# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40f0813a2190f24e05048762a8cdff733f0b1972db016432b3c4a627dd10a8a8d63e85e543852ba1ee4097c3c8f1e49c1453a35be9025f08efd93ded17141672

test:
  secret_key_base: 8edb14dbe8ef7980256597e66803195d3001b29dc314129ca359f3c5022bcdd2141c307c060872d93febdffd13718ef1734de8acdb59fe8760c039c7e5bd0eb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
